spring:
  application:
    name: Config-Dev

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    refresh:
      enable: true
    service-url:
      defaultZone:  https://serviceregitsry-production.up.railway.app/eureka