eureka:
  instance:
#     prefer-ip-address: true
    hostname: peer1
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    refresh:
      enable: true
    service-url:
      defaultZone:  http://104.196.232.237:8761/eureka/
